### PR TITLE
zephyr: Convert to new FLASH_AREA macros

### PR DESCRIPTION
**Pull request by galak**
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by utzig** [comment]
Shouldn't this go to https://github.com/apache/mynewt-mcumgr?

**Comment by galak** [comment]
> Shouldn't this go to https://github.com/apache/mynewt-mcumgr?

In theory, but that's the responsibility of whomever is maintaining this repo.

**Comment by nvlsianpu** [comment]
> In theory, but that's the responsibility of whomever is maintaining this repo.

This is not theoretical, so far most of stuff were merged firs in the upstream. 2-way synchronization is costly and error-prone. This is for the release (please deny) so can't wait for sych a flow I guess.
You can post a upstream PR from the same branch.

**Comment by carlescufi** [comment]
@nvlsianpu or @de-nordic would you mind posting this upstream?

**Pull request merged**
