### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by de-nordic**
Synch with origin running master revision: https://github.com/apache/mynewt-mcumgr/commit/98e8f320b487a775f49bf554ea29fe8958ab506f
Right after https://github.com/apache/mynewt-mcumgr/pull/71 merge

### CODE REVIEW

**Comment by carlescufi** [comment]
Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?

**Comment by utzig** [comment]
> Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?

I would second this, if you are just mirroring commits here, you can just make `apache/mynewt-mcumgr` the default module or do an automatic mirror script that keeps pulling from there (and there's no need for reviews since things are reviewed there).

**Comment by carlescufi** [comment]
> > Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?
> 
> I would second this, if you are just mirroring commits here, you can just make `apache/mynewt-mcumgr` the default module or do an automatic mirror script that keeps pulling from there (and there's no need for reviews since things are reviewed there).

The problem is that Zephyr doesn't allow as policy linking to 3rd-party repos in its manifest, due to concerns about bisectability if the non-Zephyr repo is ever deleted. So we need to keep a mirror in some way, the question is how, especially since we need to keep backwards compatibility to older manifest revisions.

**Comment by de-nordic** [comment]
> 
> 
> Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?

You mean a blob like 0a7149965a5684a539213e9295115d6ee90be716

**Comment by carlescufi** [comment]
> > Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?
> 
> You mean a blob like [0a71499](https://github.com/zephyrproject-rtos/mcumgr/commit/0a7149965a5684a539213e9295115d6ee90be716)

yes, we shouldn't mix commits with snapshots should we?

**Comment by de-nordic** [comment]
> 
> 
> > > Shouldn't we do this with a snapshot like we did the last time? I don't think we should mix snapshots with usptream commits?
> > 
> > 
> > You mean a blob like [0a71499](https://github.com/zephyrproject-rtos/mcumgr/commit/0a7149965a5684a539213e9295115d6ee90be716)
> 
> yes, we shouldn't mix commits with snapshots should we?

Done.

**Comment by carlescufi** [comment]
thanks, will approve but merging needs to wait until we have a green build in https://github.com/zephyrproject-rtos/zephyr/pull/21825

**Comment by nvlsianpu** [comment]
@carlescufi ^^ Is green.

**Pull request merged**
