### PR TITLE
snapshot: Update mcumgr to commit 0bb466 from upstream

### PR DESCRIPTION
**Pull request by utzig**
The commit applies changes that have appeared between the last snapshot
update from the upstream:
  apache/mynewt-mcumgr 8d087a7e0e5485394419d10051606c92d68d2111
and the current top on the upstream:
  apache/mynewt-mcumgr 0bb466c34e4fe863733a929baa8f51981263ce3d

### CODE REVIEW

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Comment by de-nordic** [comment]
@utzig Can you update the PR to take in the newest changes to apache/mcumgr - just add another snapshot commit on top? It will not go through till 2.4 is complete, probably, so at least all the changes that are appearing could be included. 
I could do the separate PR for that, although it would be confusing if there would be two PRs with snapshot update waiting for review/merge.

**Comment by utzig** [comment]
> @utzig Can you update the PR to take in the newest changes to apache/mcumgr

Done.

**Comment by de-nordic** [comment]
@utzig Thanks!

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
@utzig and @de-nordic this is still applicable right?

**Comment by utzig** [comment]
> @utzig and @de-nordic this is still applicable right?

I think I need to add https://github.com/apache/mynewt-mcumgr/commit/8ee7ad55868e415a0837ec3baf7630be8609d9f2

**Comment by utzig** [comment]
> @utzig and @de-nordic this is still applicable right?

Yes.

**Comment by de-nordic** [comment]
> 
> 
> > @utzig and @de-nordic this is still applicable right?
> 
> Yes.

Yes

**Comment by de-nordic** [comment]
I will merge it.

**Pull request merged**
