### PR TITLE
[DNM] upmerge: synchronize up to mynewt-mcumgr 607995c (--allow-unrelated-histories)

### PR DESCRIPTION
**Pull request by nvlsianpu**
Synchronization was done via
git merge origin/master
--allow-unrelated-histories
--strategy-option theirs

As histories are merged now so future upmerge from/backmerge to  mynewt-mcumgr will be easy.
code base effect is the same as in #5

Origin: mcumgr
License: Apache 2.0
URL: https://github.com/apache/mynewt-mcumgr
Commit: 607995c
Purpose: code-base synchronization
Maintained-by: External

Signed-off-by: Andrzej Puzdrowski andrzej.puzdrowski@nordicsemi.no

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@carlescufi

**Comment by carlescufi** [comment]
@nvlsianpu so how does this work? This PR contains the full history of mcumgr right? not sure why it does have it. Would it be possible to just do a regular merge?

**Comment by carlescufi** [comment]
We are discussing this right now with @nashif. So hold off until we have a decision please.

**Comment by nvlsianpu** [comment]
> @nvlsianpu so how does this work? This PR contains the full history of mcumgr right? not sure why it does have it. Would it be possible to just do a regular merge?

Yes it will be possible to do regular merge from and to parent repo (I checked that). This repo doesn't contain parent history as this repo was extracted from zephyr-rtos commit to formed ext/ directory (somehow I suppose).

**Comment by nvlsianpu** [comment]
@carlescufi ^^

**Comment by nvlsianpu** [comment]
@nashif ping

**Comment by nvlsianpu** [comment]
no longer needed

**Pull request closed without merging**
