### PR TITLE
img_mgmt: Fix bug with not resetting upload status

### PR DESCRIPTION
**Pull request by nordicjm**
Fixes an issue with the upload status not being set if an error occurs or if the slot is erased, which would then wrongly cause the upload to continue at a non-zero offset, skipping uploading missing data.

### CODE REVIEW

**Comment by nordicjm** [comment]
@de-nordic

**Comment by de-nordic** [comment]
> @de-nordic

For 2.7 fixes you need to follow this: https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html

**Comment by nordicjm** [comment]
> For 2.7 fixes you need to follow this: https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html

That guide doesn't really make sense, upstream has long moved on to mcumgr 0.3.0, whilst v2.7 is using 0.2.0, so applying a fix upstream is going to pull in a lot of unknown changes, including using zephyr/ prefixes for includes which is a compilation failure for zephyr 2.7

**Comment by de-nordic** [comment]
Is this related to the issue: https://github.com/zephyrproject-rtos/zephyr/pull/46203?

**Comment by nordicjm** [comment]
> Is this related to the issue: https://github.com/zephyrproject-rtos/zephyr/pull/46203?

Not that issue but this issue https://github.com/zephyrproject-rtos/zephyr/issues/51798 essentially a client starts an upload, stops, does an erase, then continues the upload, os_mgmt tells it to start from part the way through the upload, despite the data having just been erased.

**Comment by de-nordic** [comment]
> > For 2.7 fixes you need to follow this: https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html
> 
> That guide doesn't really make sense, upstream has long moved on to mcumgr 0.3.0, whilst v2.7 is using 0.2.0, so applying a fix upstream is going to pull in a lot of unknown changes, including using zephyr/ prefixes for includes which is a compilation failure for zephyr 2.7

So this is backport of https://github.com/zephyrproject-rtos/zephyr/pull/51841. Backport does not have to be 1:1, as it is never possible, nevertheless this is backport so the guide applies.

**Comment by nordicjm** [comment]
What is the guide saying then, submit it upstream to https://github.com/apache/mynewt-mcumgr then bring it down from here? Because if so then that's not going to work since mcumgr has moved on to 0.3.0, not 0.2.0 as used by the LTS

**Comment by de-nordic** [comment]
> What is the guide saying then, submit it upstream to https://github.com/apache/mynewt-mcumgr then bring it down from here? Because if so then that's not going to work since mcumgr has moved on to 0.3.0, not 0.2.0 as used by the LTS

```

The fix, not present upstream and not relevant for the current version of Zephyr, is

    directly applied to the v2.7-branch.

```
https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html#creating-a-bug-report
https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html#creating-backport-pull-requests

All apply to Zephyr port of mcumgr.
Upstream in the guide is only mentioned when they fix something upstream and we want it in the 2.7.

The https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html#creating-backport-pull-requests predicts bringing stuff directly from Zephyr repo.

**Review by de-nordic — CHANGES_REQUESTED** [review]
Can you please create the `backport-zephyr-51841-to-v2.7-branch` branch, as described in https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr_backporting.html#merging-a-backported-fix, push it to mcumgr and request merge from that branch to v2.7-branch?

**Comment by nordicjm** [comment]
> Can you please create the backport-zephyr-51841-to-v2.7-branch branch

I can't, I have no permissions in this repo

**Comment by de-nordic** [comment]
> > Can you please create the backport-zephyr-51841-to-v2.7-branch branch
> 
> I can't, I have no permissions in this repo

Can you check now?

**Comment by nordicjm** [comment]
Done, moved to https://github.com/zephyrproject-rtos/mcumgr/pull/48

**Pull request closed without merging**
