### PR TITLE
mcumgr: zephyr port os enhancement

### PR DESCRIPTION
**Pull request by lgl88911**
This patch add two new features:
 - show task name
 - show task stack usage

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/15820

Signed-off-by: Frank Li <lgl88911@163.com>

### CODE REVIEW

**Comment by mbolivar** [comment]
Thanks for this! Can you please tell me how to test it out? I have a lot of nRF52 hardware which supports mcumgr, so if you can tell me a Zephyr sample to build and some mcumgr commands to run, I will be glad to try it.

**Comment by lgl88911** [comment]
@mbolivar You can use the sampes "smp_svr" and refer my config:
https://gitee.com/lgl88911/nrf52_moderate/blob/master/apps/smp_svr/prj.conf
below config must be set for test the pr:
```
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_INIT_STACKS=y

CONFIG_MCUMGR=y
```
flash image and do the shell cmd :
mcumgr --conntype serial --connstring=/dev/ttyUSB0,baud=115200 taskstat
if the pr valid,you may be see:
```
      task pri tid  runtime      csw    stksz   stkuse last_checkin next_checkin
      idle  15   1        0        0       80       12        0        0
      main   0   2        0        0      256       56        0        0
  sysworkq 255   0        0        0      512      332        0        0

```

if no patch,you may be see:
```
      task pri tid  runtime      csw    stksz   stkuse last_checkin next_checkin
      -1  15   1        0        0       0       0        0        0
      0   0   2        0        0      0       0        0        0
  -1 255   0        0        0      0      0        0        0

```

**Comment by mbolivar** [comment]
Frank Li <notifications@github.com> writes:

> @mbolivar You can use the sampes "smp_svr" and refer my config:

Thanks!

> https://gitee.com/lgl88911/nrf52_moderate/blob/master/apps/smp_svr/prj.conf

I tried this file on nrf52840_pca10056 but got a build error. I was able
to get past the build error by manually adding `CONFIG_NET_BUF=y`.

> below config must be set for test the pr:
> ```
> CONFIG_THREAD_MONITOR=y
> CONFIG_THREAD_STACK_INFO=y
> CONFIG_THREAD_NAME=y
> CONFIG_INIT_STACKS=y
>
> CONFIG_MCUMGR=y
> ```
> flash image and do the shell cmd :
> mcumgr --conntype serial --connstring=/dev/ttyUSB0,baud=115200 taskstat

When I tried this, I got "NMP timeout" and other errors. But I think
this is because of problems with my computer. I will try again tomorrow
on another computer. Sorry for the extra wait and thanks for your patience.

**Comment by lgl88911** [comment]
@mbolivar About “NMP timeout”， you can try:
1. before do "mcumgr --conntype serial" confirm the /dev/ttyUSB0 can't be opened by other process
2. use another usb2tty connect hw. I know DAPLink CDC can't work well with mcumgr
3. using mcumgr over bt，config option：
```
CONFIG_MCUMGR_SMP_BT=y
```
use shell cmd：
mcumgr --conntype ble --connstring ctlr_name=hci0,peer_name='Zephyr' taskstat

**Comment by mbolivar** [comment]
Hi @lgl88911, I was able to confirm your results on another computer. (I tried BT also, but ran into another bug: https://github.com/zephyrproject-rtos/zephyr/issues/16803#issuecomment-501762936).

@carlescufi @nvlsianpu @nashif I think this patch looks good and I have tested it on nrf52840_pca10056. Can you please review and merge if OK?

**Comment by carlescufi** [comment]
@lgl88911 
This should be sent upstream to mcumgr though:
https://github.com/apache/mynewt-mcumgr/tree/master/cmd/os_mgmt/port/zephyr/src

Then we can import the new version into zephyr

**Comment by carlescufi** [comment]
> @lgl88911
> This should be sent upstream to mcumgr though:
> https://github.com/apache/mynewt-mcumgr/tree/master/cmd/os_mgmt/port/zephyr/src
> 
> Then we can import the new version into zephyr

That said I see we have additional commits that have not been pushed upstream, which is a problem. I suggest we merge this and then send a batch of commits upstream all together. @mbolivar, @nashif, @nvlsianpu  you ok with that?

**Comment by mbolivar** [comment]
> That said I see we have additional commits that have not been pushed upstream, which is a problem. I suggest we merge this and then send a batch of commits upstream all together. @mbolivar, @nashif, @nvlsianpu you ok with that?

That's fine with me; I should have realized this had an actively maintained upstream. Sorry about that.

**Comment by mbolivar** [comment]
@lgl88911 when this gets merged, can you send a PR to the zephyr repository updating the west.yml file to point at the new SHA?

**Comment by lgl88911** [comment]
@mbolivar @nashif 
I pull a pr for update SHA https://github.com/zephyrproject-rtos/zephyr/pull/16842, but , look like need merge the pr first, then 16842 pr CI check will pass

**Comment by lgl88911** [comment]
@mbolivar @nashif I create pr https://github.com/zephyrproject-rtos/zephyr/pull/16844, look like need merge the pr first, then pr 16844 CI check to pass

**Comment by carlescufi** [comment]
@de-nordic and @nvlsianpu can you please review this?

**Comment by de-nordic** [comment]
> 
> 
> @de-nordic and @nvlsianpu can you please review this?

Sorry it takes long. I have problems building smp_svr with it, from zephyrproject-rtos/zephyr#16844 . Basically I get this:
```
Zephyr version: 1.14.99
-- Selected BOARD nrf52840_pca10056
CMake Error at /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/toolchain/zephyr/host-tools.cmake:46 (include):
  include could not find load file:

    /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/toolchain/zephyr/0.10.3/host-tools.cmake
Call Stack (most recent call first):
  /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/host-tools.cmake:3 (include)
  /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/app/boilerplate.cmake:412 (include)
  CMakeLists.txt:12 (include)


-- Found west: /home/doer/.local/bin/west (found suitable version "0.6.99", minimum required is "0.5.6")
CMake Error at /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/toolchain/zephyr/generic.cmake:7 (include):
  include could not find load file:

    /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/toolchain/zephyr/0.10.3/generic.cmake
Call Stack (most recent call first):
  /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/generic_toolchain.cmake:64 (include)
  /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/app/boilerplate.cmake:428 (include)
  CMakeLists.txt:12 (include)


-- Loading /home/doer/nordic-src/zephyrproject-vanilla/zephyr/boards/arm/nrf52840_pca10056/nrf52840_pca10056.dts as base
-- Overlaying /home/doer/nordic-src/zephyrproject-vanilla/zephyr/dts/common/common.dts
CMake Error at /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/dts.cmake:126 (message):
  command failed with return code: No such file or directory
Call Stack (most recent call first):
  /home/doer/nordic-src/zephyrproject-vanilla/zephyr/cmake/app/boilerplate.cmake:429 (include)
  CMakeLists.txt:12 (include)
```

@mbolivar, @lgl88911 please advise.

I am right now getting sdk v0.10.1 to try building with it.

**Comment by nvlsianpu** [comment]
That said I see we have additional commits that have not been pushed upstream, which is a problem. I suggest we merge this and then send a batch of commits upstream all together. @mbolivar, @nashif, @nvlsianpu you ok with that?

Sounds fine to me. Actually we have done this like this up to now a few times.

**Comment by de-nordic** [comment]
I have been able to build it after switching SDK to 0.10.1, but still It does not work for me:
```
$$ sudo ~/go/bin/mcumgr -t 25 --conntype serial --connstring=/dev/ttyUSB0,baud=115200 taskstat
Error: 2
```

I use following versions:
```
zephyrproject-rtos: 13a2440af6587001602b6ed43f6da0f476533dfa
modules/lib/mcumgr: ee2cb08d76efa7791ac7a79fed5a73f549bf6abd (pulled by west)
mynewt-mcumgr: 92e343190081476f9cde016b728a1836ab20f44b
mynewt-mcumgr-cli: 62a813605b2a1cba2c36d8373c0e8fe91015bcb3
```

**Comment by nvlsianpu** [comment]
pleas rebase onto newest master, some include path were changed in zephyr so can't build this with zephyr master

**Comment by lgl88911** [comment]
@nvlsianpu @de-nordic Thanks for your verify, last commit is too old, I update the as @nvlsianpu suggest. It can work in sdk 0.10.3

**Comment by nvlsianpu** [comment]
@lgl88911 Can you open mirror PR to https://github.com/apache/mynewt-mcumgr.
We usually merge features there and then just synchronize this repo with the apache.

cc @de-nordic Can you review this?

**Comment by lgl88911** [comment]
> @lgl88911 Can you open mirror PR to https://github.com/apache/mynewt-mcumgr.
> We usually merge features there and then just synchronize this repo with the apache.
> 
> cc @de-nordic Can you review this?

@nvlsianpu I pull a pr https://github.com/apache/mynewt-mcumgr/pull/81, please review, Thanks!

**Comment by de-nordic** [comment]
> 
> cc @de-nordic Can you review this?

Yes, just give me current PR for west.yml changes in Zephyrproject-rtos/zephyr that take this in.

**Comment by lgl88911** [comment]
> Yes, just give me current PR for west.yml changes in Zephyrproject-rtos/zephyr that

@de-nordic 
I submitted another PR apache/mynewt-mcumgr#81 as @nvlsianpu  suggested by xx, but I don't quite understand what you want me to do. My understanding flow is:
1. upstream merge PR --> mcumgr owner?
2. sync upstream to zephyr module --> mcumgr of zephyr owner?
3. Submit a PR for west.yaml to update the version of mcumgr --> me?

**Comment by de-nordic** [comment]
> 
> I am not sure if this is correct, please help check this pr
> [zephyrproject-rtos/zephyr#25711](https://github.com/zephyrproject-rtos/zephyr/pull/25711)

You did the PR correctly.

I am still trying to test your changes, sorry for lagging but I keep on getting error 2 during transfer.
Does anyone else got that problem?

**Comment by lgl88911** [comment]
> > I am not sure if this is correct, please help check this pr
> > [zephyrproject-rtos/zephyr#25711](https://github.com/zephyrproject-rtos/zephyr/pull/25711)
> 
> You did the PR correctly.
> 
> I am still trying to test your changes, sorry for lagging but I keep on getting error 2 during transfer.
> Does anyone else got that problem?

I don't confirm what error 2 means
Can you show me the error log, test whether it is UART or BT？

**Comment by lgl88911** [comment]
@mbolivar @carlescufi @de-nordic @nvlsianpu @nashif 
Since this modification will be from upstream sync, can this PR be close? I
if other review suggestions, we can go to apache/mynewt-mcumgr#81 to discuss?

**Comment by de-nordic** [comment]
> 
> I don't confirm what error 2 means

No worries, seems to be problem with my board and finally everything stopped working.I had to complete erase it.

**Comment by utzig** [comment]
> > I don't confirm what error 2 means
> 
> No worries, seems to be problem with my board and finally everything stopped working.I had to complete erase it.

I was actually testing this now and got the same error. It happens, at least on the `frdm_k64f`, because there is not enough memory for doing the encoding of all tasks, so I had to set `CONFIG_MCUMGR_BUF_SIZE=512` to make it work. The output "alignment" looks a bit funny though! :-)

```
      task pri tid  runtime      csw    stksz   stkuse last_checkin next_checkin
   idle 00  15   3        0        0       80       14        0        0
   logging  14   2        0        0      192       43        0        0
      main   0   4        0        0      256       72        0        0
  shell_uart  14   1        0        0      512      150        0        0
  sysworkq 255   0        0        0      512      112        0        0
```

**Comment by de-nordic** [comment]
@utzig good finding! OK this needs to be somehow noted but it seems that it may depend on actual number of tasks, description, etc, and might as well affect the code without this PR.
Right now I can not get the error 2, and before erasing the board I got it 100% of time.

**Comment by lgl88911** [comment]
upstream has merged this modification, and another pr https://github.com/zephyrproject-rtos/mcumgr/pull/25 will sync back to zephyr, so close this PR

**Pull request closed without merging**
